### ISSUE TITLE
tag as "community PR" when PR author is not in the organization

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-bot#19]
In order to better track PRs from the Qiskit community, it would be great if qiksit-bot could tag as `community PR` PRs that are not from members of the organization. The data seems to be available as `author_association` in the PR object https://api.github.com/repos/Qiskit/qiskit-terra/pulls?state=open

**Comment by mtreinish** [comment]
This should be fairly easy  to implement. I checked and the webhook api payload for pull requests (which is subtlety different from the rest api you linked) has the same field:

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request

To do this the easiest thing is to just add an additional option to the local repo config file to map author association to the github label to use. Then basically add a parallel function call in api.py to what I added in #18 which calls PyGithub's [`PullRequest.add_to_labels()`](https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.add_to_labels) to assign the label in the appropriate conditions.
