### ISSUE TITLE
Bump each element version after release

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-bot#3]
The only manual step that's still part of the release workflow (besides reviewing, approving, and merging PRs) is bumping the element version after a successful release. For example, see:

https://github.com/Qiskit/qiskit-terra/pull/3803

We should add support to the release automation path of qiskit-bot to do this automatically. This way it's less error prone and something we won't forget after pushing a release.

**Comment by Eric-Arellano** [comment]
Irrelevant now that the metapackage is removed.
