### ISSUE TITLE
Make notifications varied so that people don't automatically ignore it

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-bot#31]
In private discussion with @mtreinish, we realize that people tend to ignore the qiskit-bot PR [notification](https://github.com/Qiskit/qiskit-bot/blob/master/qiskit_bot/notifications.py) (for example: https://github.com/Qiskit/qiskit-terra/pull/8592#issuecomment-1222065215). A wild idea we have is to use some kind of AI service to generate the same message using different tones each time to make it more varied so that people will pay attention to it.

The simplest way to implement this is just to generate a bunch of these messages offline and store it in this repo and the bot randomly pick one version of it each time.

**Comment by mtreinish** [comment]
Yeah, I'd worry about using an remote api call to a text generation service as part of the bot's operation (while technically possible it seems like a lot of complexity for just notifications). But having support for multiple message and switching between some different tones and similar messages might help make people look it, that's definitely a good starting point. We should also ensure that the configurable message text supports this feature too (so people can provide multiple message texts and the bot will switch between them)

**Comment by HuangJunye** [comment]
I decided not to work on this due to change of priorities. Unassigned myself.

**Comment by Eric-Arellano** [comment]
Rather than changing the text, we took the approach of reducing the noise via https://github.com/Qiskit/qiskit-bot/pull/39.
