### ISSUE TITLE
comment on visualization changes with binder for visualization testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-bot#34]
It would be great if the bot can comment when somebody modifies qiskit/visualization/ with the binder to test the visualization module: `https://mybinder.org/v2/gh/<github_user>/<repo>/<branch>?urlpath=apps/test/ipynb/mpl_tester.ipynb` and that can locally be run with `jupyter notebook test/ipynb/mpl_tester.ipynb`.

**Comment by Eric-Arellano** [comment]
@1ucian0 is this still relevant? I'm trying to clean up GitHub issues.

**Comment by 1ucian0** [comment]
nope.. it can be removed. Thanks!
